/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "sanctum.csrf-cookie": [],
    "home": [],
    "docs": [],
    "login.discord": [],
    "guilds.selector": [],
    "guilds.select": [
        {
            "name": "guild",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "guild.setup.show": [],
    "guild.setup.features.save": [],
    "guild.setup.feature.save": [
        {
            "name": "feature_id",
            "required": true
        }
    ],
    "guild.setup.finish": [],
    "guild.users.index": [],
    "guild.users.store": [],
    "guild.users.update": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.image": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.duties": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.punishments": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.image.show": [
        {
            "name": "image",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.image.store": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.image.delete": [
        {
            "name": "image",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.delete": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "guild.users.bulk.delete": [],
    "duty.index": [],
    "duty.active": [],
    "duty.toggle": [
        {
            "name": "guild_user",
            "required": true,
            "binding": "id"
        }
    ],
    "duty.store": [],
    "duty.update.status": [],
    "duty.update": [
        {
            "name": "duty",
            "required": true,
            "binding": "id"
        }
    ],
    "duty.bulk.delete": [],
    "duty.delete": [
        {
            "name": "duty",
            "required": true,
            "binding": "id"
        }
    ],
    "punishment.index": [],
    "punishment.store": [],
    "punishment.bulk.delete": [],
    "punishment.delete": [
        {
            "name": "punishment",
            "required": true,
            "binding": "id"
        }
    ],
    "items.index": [],
    "items.store": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
